export const SIDEBAR_OPEN = 'SIDEBAR_OPEN'
export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE'
export const GET_PRODUCTS_BEGIN = 'GET_PRODUCTS_BEGIN'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR'
export const GET_SINGLE_PRODUCT_BEGIN = 'GET_SINGLE_PRODUCT_BEGIN'
export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS'
export const GET_SINGLE_PRODUCT_ERROR = 'GET_SINGLE_PRODUCT_ERROR'
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS'
export const SET_GRIDVIEW = 'SET_GRIDVIEW'
export const SET_LISTVIEW = 'SET_LISTVIEW'
export const UPDATE_SORT = 'UPDATE_SORT'
export const SORT_PRODUCTS = 'SORT_PRODUCTS'
export const UPDATE_FILTERS = 'UPDATE_FILTERS'
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS'
export const CLEAR_FILTERS = 'CLEAR_FILTERS'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'
export const TOGGLE_CART_ITEM_AMOUNT = 'TOGGLE_CART_ITEM_AMOUNT'
export const CLEAR_CART = 'CLEAR_CART'
export const COUNT_CART_TOTALS = 'COUNT_CART_TOTALS'


export const SHOW_LOGIN = 'SHOW_LOGIN'
export const SHOW_SIGNUP = 'SHOW_SIGNUP'
export const LOGIN_USER = 'LOGIN_USER'
export const SIGNUP_USER = 'SIGNUP_USER'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const SIGNUP_FAILED = 'SIGNUP_FAILED'
export const AUTH_FAILURE = 'AUTH_FAILURE'
export const CLEAR_ALERTS = 'CLEAR_ALERTS'
export const LOGOUT = 'LOGOUT'
export const LOGIN_BEGIN = 'LOGIN_BEGIN'

export const GET_VEHICLES_SUCCESS = 'GET_VEHICLES_SUCCESS'
export const GET_VEHICLES_BEGIN = 'GET_VEHICLES_BEGIN'
export const GET_VEHICLES_ERROR = 'GET_VEHICLES_ERROR'

export const ADD_VEHICLES_SUCCESS = 'ADD_VEHICLES_SUCCESS'
export const ADD_VEHICLES_BEGIN = 'ADD_VEHICLES_BEGIN'
export const ADD_VEHICLES_ERROR = 'ADD_VEHICLES_ERROR'

export const UPDATE_VEHICLES_SUCCESS = 'UPDATE_VEHICLES_SUCCESS'
export const UPDATE_VEHICLES_BEGIN = 'UPDATE_VEHICLES_BEGIN'
export const UPDATE_VEHICLES_ERROR = 'UPDATE_VEHICLES_ERROR'

export const GET_SINGLE_VEHICLE_BEGIN='GET_SINGLE_VEHICLE_BEGIN'
export const GET_SINGLE_VEHICLE_SUCCESS = 'GET_SINGLE_VEHICLE_SUCCESS'
export const GET_SINGLE_VEHICLE_ERROR = 'GET_SINGLE_VEHICLE_ERROR'

export const DELETE_VEHICLE_BEGIN='DELETE_VEHICLE_BEGIN'
export const DELETE_VEHICLE_SUCCESS='DELETE_VEHICLE_SUCCESS'
export const DELETE_VEHICLE_ERROR='DELETE_VEHICLE_ERROR'


export const LOAD_VEHICLES = 'LOAD_VEHICLES'
export const FILTER_VEHICLES = 'FILTER_VEHICLES'

export const GET_MAINTENANCES_SUCCESS = 'GET_MAINTENANCES_SUCCESS'
export const GET_MAINTENANCES_BEGIN = 'GET_MAINTENANCES_BEGIN'
export const GET_MAINTENANCES_ERROR = 'GET_MAINTENANCES_ERROR'

export const ADD_MAINTENANCE_BEGIN = 'ADD_MAINTENANCE_BEGIN'
export const ADD_MAINTENANCE_SUCCESS='ADD_MAINTENANCE_SUCCESS'
export const ADD_MAINTENANCE_ERROR = 'ADD_MAINTENANCE_ERROR'

export const UPDATE_MAINTENANCE_BEGIN = 'UPDATE_MAINTENANCE_BEGIN'
export const UPDATE_MAINTENANCE_SUCCESS='UPDATE_MAINTENANCE_SUCCESS'
export const UPDATE_MAINTENANCE_ERROR = 'UPDATE_MAINTENANCE_ERROR'

export const DELETE_MAINTENANCE_BEGIN = 'DELETE_MAINTENANCE_BEGIN'
export const DELETE_MAINTENANCE_SUCCESS = 'DELETE_MAINTENANCE_SUCCESS'
export const DELETE_MAINTENANCE_ERROR = 'DELETE_MAINTENANCE_ERROR'

export const GET_VEHICLE_CATEGORIES_BEGIN='GET_VEHICLE_CATEGORIES_BEGIN'
export const GET_VEHICLE_CATEGORIES_SUCCESS='GET_VEHICLE_CATEGORIES_SUCCESS'
export const GET_VEHICLE_CATEGORIES_ERROR='GET_VEHICLE_CATEGORIES_ERROR'

export const ADD_NOTIFICATION_BEGIN = 'ADD_NOTIFICATION_BEGIN'
export const ADD_NOTIFICATION_SUCCESS = 'ADD_NOTIFICATION_SUCCESS'
export const ADD_NOTIFICATION_ERROR = 'ADD_NOTIFICATION_ERROR'

export const UPDATE_NOTIFICATION_BEGIN = 'UPDATE_NOTIFICATION_BEGIN'
export const UPDATE_NOTIFICATION_SUCCESS = 'UPDATE_NOTIFICATION_SUCCESS'
export const UPDATE_NOTIFICATION_ERROR = 'UPDATE_NOTIFICATION_ERROR'

export const GET_NOTIFICATION_BEGIN = 'GET_NOTIFICATION_BEGIN'
export const GET_NOTIFICATION_SUCCESS = 'GET_NOTIFICATION_SUCCESS'
export const GET_NOTIFICATION_ERROR = 'GET_NOTIFICATION_ERROR'

export const DELETE_NOTIFICATION_BEGIN = 'DELETE_NOTIFICATION_BEGIN'
export const DELETE_NOTIFICATION_SUCCESS = 'DELETE_NOTIFICATION_SUCCESS'
export const DELETE_NOTIFICATION_ERROR = 'DELETE_NOTIFICATION_ERROR'
